# docker-compose.yml (Dev)

services:
  # Base de données MySQL
  database:
    image: mysql:8.0
    container_name: mysql_db_todolist
    restart: unless-stopped
    env_file:
      - server/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Backend Node.js
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nodejs_backend_todolist
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - server/.env

    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  # Frontend React (Dev Server)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_frontend_todolist
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env

    depends_on:
      - server
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    networks:
      - app-network

volumes:
  mysql_data:
  client_node_modules:
networks:
  app-network:
